services:
  - type: web
    name: yt-summ-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
